#!/bin/bash

INTERFACES=$(ip addr | grep -E '^[0-9]+: [a-z0-9]*:' | sed  -r 's/^[0-9]+: ([a-z0-9]*): .*/\1/' | sed '/lo/d')

OUT=""

for ifc in $INTERFACES; do
	IP=$(ip addr show $ifc | grep "inet " | sed  -r 's#.*inet ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+).*#\1#')
	PROF=$(netctl list | grep "* $ifc" | sed -r "s/\* ($ifc-.*)/\1/")$(netctl-auto list | grep "* $ifc" | sed -r "s/\* ($ifc-.*)/\1/")
	if [ -n "$IP" ]; then
		if [ -n "$PROF" ]; then
			OUT="$OUT$PROF $IP - "
		else
			OUT="$OUT$ifc $IP - $"
		fi
	fi
done

OUT="${OUT//  / }"
echo -e "${OUT::-3}"
